<h3>Hiroshima</h3>
<p><em>"Strike a bell in <b>Hiroshima</b> park"</em> - Hercules (Species Deceases)<br>
On August 6th 1945, Hiroshima became the first city in the world to be struck by an atomic bomb, dropped by the United States Air Force. Most of the city was destroyed, and estimates of the number killed have ranged higher than 200,000. Deaths through radiation and poising have mounted through the years. Peter Garrett was heavily influenced during the recording of Red Sails in the Sunset, when he went to visit some of the survivors of the drop.<br>
Co-ordinates: 34.24N 132.27E</p>