<h3>Indian Ocean</h3>
<p><em>"From the great gibber plain, to the <b>Indian Ocean</b>"</em> - The Great Gibber Plain (Redneck Wonderland)<br>
The Indian Ocean is the third largest ocean and is located between Africa, Asia, Australia and Antartica. It occupies around one-fifth of the worlds oceans space. It's total area is greater than 28 million square miles, and has an average depth of around 12,000 feet. It's deepest point is the Java trench (24,442 feet).<br>
Co-ordinates: 10.00S 70.00E</p>