<h3>Brisbane</h3>
<em>"20 hours to <b>Brisbane</b> on a night prowl play,<br>20 hours to Brisbane... Where's Brisbane...?"</em> - Koala Sprint (Head Injuries)<br>
"Brisbane is the capital of the state of Queensland, lying near it's southeast corner, and is the third largest city in Australia. The site was selected in 1824 by the explorer, John Oxley, and was named after Sir Thomas M. Brisbane, a governor of New South Wales, who sent a party from Sydney the following year to settle the area. It was probably mentioned by Midnight Oil due to it's favourable weather and close proximity to good surfing beaches." - <em>(from the Encyclopaedia Brittanica)</em><br>
Co-ordinates: 27.28S 153.02E<br>
Pg 171a<p>