<h3>Burnie</h3>
<em><b>Burnie</b></em> - Burnie (Place Without a Postcard)<br>
"Burnie is a town and port in northern Tasmania. It is situated on Emu Bay at the mouth of the Emu River, and was established in 1829 by the Van Diemen's Land Company as Emu Bay Settlement. The settlement was renamed to honour a company director, William Burnie, nad was declared a town in 1866. In the 1870s it served as an outport for the tin mine at Mt. Bischoff, and it was constituted a municipality in 1908. It is the northern-most port served by the Sydney-Tasmania ferry and is the commercial centre for north-western Tasmania." - <em>(from the Encyclopaedia Brittanica)</em><br>
Co-ordinates: 41.04S 145.54E<br>
Pg 166<p>