<h3>Darwin</h3>
<em>"<b>Darwin</b> down to Alice Springs"</em> - Kosciuszko (Red Sails in the Sunset)<br>
<em>"We'll be staying at the Roma Bar"</em> - Truganini (Earth and Sun and Moon)<br>
"Darwin - a city with a population of around 55,000, average age 25. A city in which, in the depths of winter, you can sit on the beach at sunset, watching an iridescent orange ball of light sinking into the blue waters of Fanny Bay. And not feel cold. Where you can stretch beneath palmtrees watching wedge tails, kites and hawkes drift on the breeze, soaring high on the strength of an unseen thermal with the mere twitch of a wingtip. Where, on a winter's evening, you can wander down to the Botanic Gardens in shorts and a singlet with an armful of beer and join people sitting around..." <em>(from Strict Rules by Andrew McMillan)</em><br>
The <em>Roma Bar</em> is not (as originally stated here) in Roma, Queensland, but is in fact in Cavenagh Street, Darwin. I am reliably informed this by Andrew McMillan - "hence the monsoon reference" he says!
Co-ordinates: 12.28S 130.50E<br>
Pg 164<p>