<h3>Kintore (Mt)</h3>
<em>"From <b>Kintore</b> East to Yuendemu"</em> - Beds are Burning (Diesel and Dust)<br>
As well as being a mountain, Kintore is also the name of a range in the area, and is also an Aboriginal settlement in central Australia. The settlement began as an out-station but quickly grew to become the nucleus of a spread of smaller out-stations. Midnight Oil visited Kintore on their Black Fella White fella tour of the outback in 1986.<br>
Co-ordinates: 26.34S 130.30E<br>
Pg 163<p>