<h3>Kosciuszko</h3>
<em>"Older than <b>Kosciuszko</b>"</em> - Kosciuszko (Red Sails in the Sunset)<br>
Kosciuszko is a mountain in New South Wales - the highest peak in Australia - and is part of the Great Dividing Range. It is also the name of the National Park in which Mt Kosciuszko can be found. The mountain was named for Polish patriot Tadeusz Kosciuszko<br>
Co-ordinates: 36.27S 148.16E<br>
Pg 171b<p>