<h3>Lismore</h3>
<em>"Not the <b>Lismore</b> Road tonight"</em> - Outside World (10,9,8,7,6,5,4,3,2,1)<br>
"Lismore is a city in northeastern New South Wales. Ward Stephens first settled the site in 1843; it was later occupied by William Wilson and named by him - probably for the Scottish island of Lismore. It is a farm processing centre, and also has some light industrial development. The city has an art gallery and a museum housing aboriginal relics. It became a village in 1856, municipality in 1879, and a city in 1946." - <em>(from the Encyclopaedia Brittanica)</em><br>

Co-ordinates: 28.48S 153.17E<br>
Pg 166<br>
or Co-ordinates: 37.58S 143.20E<br>
Pg 169<p>