<h3>Mallee Cliffs National Park</h3>
<em>"From the golden reefs to the sandstone cliffs<br>
Came the sheep pens of the <b>mallee</b> plain"</em> - Stars of Warburton (Blue Sky Mining)<br>
A National Park near the border of New South Wales and Victoria, and is approximately south of Broken Hill.<br>
Mallee is also an agricultural region in the state of Victoria, producing most of it's wheat. It is a semi-arid area btween the Wimmera and Murray rivers.<br>
Note:- although the atlas entry for Mallee has been added, it has come to light that there is in a <b>mallee</b> which is a type of scubland vegetation of euclaypt species - this could be the mallee plains referred to in the song. (Mallee comes from an Aboriginal term for species of eucalypt)<br>
Co-ordinates: 34.15S 142.40E<br>
Pg 166<p>