<h3>Sydney</h3>
<em>"<b>Sydney</b>, where the nights are warm"</em> - Power and the Passion (10,9,8,7,6,5,4,3,2,)<br>
Sydney is a city and major port in southeastern Australia, and the capital of New South Wales. The largest city in Australia, Sydney is centered on the southern shore of Port Jackson. 
Sydney is one of Australia's leading industrial, commercial, financial, and transportation centers. Several of the country's largest companies are headquartered in Sydney. Port Jackson, which is spanned by the graceful, single-steel-arch Sydney Harbour Bridge, is a favorite spot for yacht owners.<br>
British explorer and navigator Captain James Cook sighted and named Port Jackson in 1770. The first European settlement in Australia was established on the site of modern Sydney by Captain Arthur Phillip in 1788. He named it Sydney Cove, after the British home secretary, Thomas Townshend, 1st Viscount Sydney. Most of the early inhabitants were convicts sent out from Great Britain, but increasing numbers of free settlers arrived during the first half of the 1800s as New South Wales was developed by sheep and cattle raisers and wheat farmers.<br>
As well as home to several million people, Sydney is also the home of Midnight Oil, where they began playing to clubs along the surfing beaches.<br>
Co-ordinates: 33.52S 151.13E<br>
Pg 170<p>

<ul><li>Bondi<br>
<em>"Then I'll catch the bus to <b>Bondi</b>"</em> - Section 5(Bus to Bondi) (Head Injuries)<br>
Famous beach in Sydney, but is also a "town" according to atlas'.<br>
Co-ordinates: 33.53S 151.17E<br>
Pg 274a<p>

<li>Chatswood<br>
<em>"It's a long way from <b>Chatswood</b> to the top of the gulf"</em> - Koala Sprint (Head Injuries)<br>
<em>"<b>Chatswood</b> wasn't built in a day"</em> - Bring on the Change (Breathe)<br>
Town/suburb of north-eastern Sydney.<br>
Co-ordinates: 33.48S 151.12E<br>
Pg 274a
</ul><p>